name: Release

on:
  push:

jobs:
  package:
    runs-on: ubuntu-latest
    environment: Webstores
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: npm clean-install-test
      env:
        LAST_FM_SECRET: ${{ secrets.LAST_FM_SECRET }}
        LAST_FM_KEY: ${{ secrets.LAST_FM_KEY }}

    - name: Package the extension
      run: |
        mkdir -p dist
        npm run package
      env:
        LAST_FM_SECRET: ${{ secrets.LAST_FM_SECRET }}
        LAST_FM_KEY: ${{ secrets.LAST_FM_KEY }}

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Create release (if tagged)
      if: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
      run: |
        hub release create -a "webextension-fip-${VERSION}.zip" ${VERSION}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
