name: Release

on:
  push:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - run: npm clean-install-test

    - name: Package the extension
      run: |
        mkdir -p dist
        npm run package

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Create release (if tagged)
      if: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
      run: |
        hub release create -a "webextension-fip-${VERSION}.zip" ${VERSION}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
